import Head from "next/head";
import { useState } from "react";
import { api } from "~/utils/api";

export default function Home() {
  const [firstName, setFirstName] = useState<string>("");
  const [lastName, setLastName] = useState<string>("");
  const [email, setEmail] = useState<string>("");
  const requestEntry = api.namePronunciationEntry.requestEntry.useMutation({
    onSuccess: () => {
      alert("Success");
    },
    onError: () => {
      alert("Error");
    },
  });

  const submitRequest = () => {
    if (!firstName || !lastName || !email) {
      alert("Please fill out all fields");
      return;
    }
    requestEntry.mutate({
      firstName,
      lastName,
      email,
    });
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <input
          type="text"
          value={firstName}
          onChange={(e) => setFirstName(e.target.value)}
          placeholder="first name"
        />
        <input
          type="text"
          value={lastName}
          onChange={(e) => setLastName(e.target.value)}
          placeholder="last name"
        />
        <input
          type="text"
          value={email}
          onChange={(e) => setEmail(e.target.value)}
          placeholder="email"
        />
        <button onClick={submitRequest}>Submit</button>
      </main>
    </>
  );
}
